### ISSUE TITLE
Can't resolve dependencies in connectkit template

### ISSUE THREAD

**Issue by eternitybro** [wevm/create-wagmi#80]
"pino-pretty", "lokijs", "encoding" are dependencies are not being met after using `yarn create wagmi --template next-connectkit --skip-git --yarn`.

<img width="828" alt="Screenshot 2023-07-18 at 1 16 39 AM" src="https://github.com/wagmi-dev/create-wagmi/assets/7077444/c909dc11-3ffe-49ac-bf10-d293cda8c7fc">

**Comment by eternitybro** [comment]
Solution found here: 
https://github.com/WalletConnect/walletconnect-monorepo/issues/1908#issuecomment-1487801131

I tried to create a PR but I do not have sufficient priviliges.

```
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  webpack: (config) => {
    config.externals.push("pino-pretty", "lokijs", "encoding");
    config.resolve.fallback = { fs: false, net: false, tls: false }
    return config
  },
}
```
Fixes the issue for me.

**Comment by sigmachirality** [comment]
Running into the same issue!
